# Enable/Disable the use of the permission-node rank system.
# Should the integrated rank system be Enabled?
enabled: true

# Rank players will start with by default.
# If no default is specified no rank will be used.
default: Member

# This weight determines which ranks are considered as staff ranks.
# Any rank with a weight higher than, or equal to what is set below will have staff permissions.
staff-weight: 10

# This weight determines which ranks are considered as admin ranks.
# Any rank with a weight higher than, or equal to what is set below will have admin permissions.
admin-weight: 20

# Create and add/remove ranks below.
# Ranks will use "Display" set below for each rank unless explicitly set in each themes ranks.yml file otherwise disabled above.
ranks:
  
  Probation:
    
    # The following variables are applicable to the "display" node.
    # Tags set in each themes "Tags" node are also applicable below.

    # [VARIABLE]     | [VALUE USE]   ; [SMALL DESCRIPTION]
    
    # \n             | Next Line     ; Send multiple lines of text.
    # %time%         | Time Stamp    ; Time the message was created.
    # %date%         | Date Stamp    ; Date the message was created.
    # %name%         | Player Name   ; Player name or disguise name.
    # %player%       | Real Name     ; Player name, ignores player disguises.
    # %rank%         | Rank          ; Rank that is being added, easier for copy/paste.
    
    # Command and permission weight.
    # The higher the weight the higher the authority.
    # If the weight is set to 0, the rank will not be able to do most things.
    # If the weight of a rank is 0 or lower, players will not be able to mask as the rank.
    # FleX default: [Probation] 0, [Member] 1, [Staff] 10+, [Admin] 20+ (See staff-weight and admin-weight above)
    
    weight: 0
    
    # Weight is used in all rank restricted FleX commands.
    # You can also inherit another ranks permissions below.

    inherit: []
    
    # Want ranks per world or even per partition?
    # Simply add the worlds name or UUID below (find in the worlds info.yml).
    # If you would like the rank to be usable in all worlds, just add an asterisk ('*') to the list.
    
    worlds:
    - '*'
    
    # A place for permission nodes.
    # Since this is a all-in-one engine, this is quite necessary instead of just using static ranks.
    
    permissions:
    - permission.one
    - permission.you-guessed-it.two
    - another.permission.etc
    
  Bot:
    weight: 1
    inherit:
    - Member
    worlds:
    - '*'
    permissions: []
  Member:
    weight: 1
    inherit: []
    worlds:
    - '*'
    permissions: []
  Donor_1:
    weight: 2
    inherit:
    - Member
    worlds:
    - '*'
    permissions: []
  Donor_2:
    weight: 3
    inherit:
    - Donor_1
    worlds:
    - '*'
    permissions:
    - flex.command.fly
  Donor_3:
    weight: 4
    inherit:
    - Donor_2
    worlds:
    - '*'
    permissions:
    - flex.command.disguise
  Donor_4:
    weight: 5
    inherit:
    - Donor_3
    worlds:
    - '*'
    permissions:
    - flex.command.disguise.keepskin
  Donor_5:
    weight: 6
    inherit:
    - Donor_4
    worlds:
    - '*'
    permissions:
    - flex.command.disguise.flip
  Donor_6:
    weight: 7
    inherit:
    - Donor_5
    worlds:
    - '*'
    permissions:
    - flex.command.disguise.chooseskin
  Donor_7:
    weight: 8
    inherit:
    - Donor_6
    worlds:
    - '*'
    permissions: []
  Map_Maker:
    weight: 7
    inherit:
    - Donor_7
    worlds:
    - '*'
    permissions: []
  VIP:
    weight: 7
    inherit:
    - Donor_7
    worlds:
    - '*'
    permissions: []
  Moderator:
    weight: 10
    inherit:
    - Donor_6
    worlds:
    - '*'
    permissions:
    - flex.command.punish
    - flex.command.flex
    - flex.command.flow
    - flex.command.teleport
  Senior_Moderator:
    weight: 10
    inherit:
    - Moderator
    worlds:
    - '*'
    permissions: []
  Developer:
    weight: 15
    inherit:
    - Senior_Moderator
    worlds:
    - '*'
    permissions:
    - flex.command.admin
    - flex.command.combat
    - flex.command.disguise.custom
    - flex.command.gamemode
  Administrator:
    weight: 20
    inherit:
    - Senior_Moderator
    worlds:
    - '*'
    permissions:
    - flex.command.admin
    - flex.command.gamemode
  Owner:
    weight: 999
    inherit:
    - Administrator
    worlds:
    - '*'
    permissions:
    - '*'
